int-----INT
main-----ID
(-----LPAREN
)-----RPAREN
{-----LBRACKET
char-----CHAR
token_char-----ID
=-----ASSIGN
'h'-----CHAR_TOKEN
;-----SEMICOLON
cout-----COUT
"hello world"-----STRING
endl-----ID
;-----SEMICOLON
int-----INT
token_number-----ID
=-----ASSIGN
666-----NUMBER
;-----SEMICOLON
int-----INT
token_number1-----ID
=-----ASSIGN
token_number-----ID
;-----SEMICOLON
return-----RETURN
0-----NUMBER
;-----SEMICOLON
}-----RBACKET
